name: flutter_base_player
description: Universal video player for flutter
repository: https://github.com/zhahouming/flutter_base_player/flutter_base_player
version: 0.1.3
homepage: https://github.com/zhahouming/flutter_base_player/flutter_base_player

flutter:
  plugin:
    platforms:
      android:
        dartPluginClass: FlutterBasePlayerVideoPlayer
      ios:
        dartPluginClass: FlutterBasePlayerMediaKitPlayer
      macos:
        dartPluginClass: FlutterBasePlayerMediaKitPlayer
      windows:
        dartPluginClass: FlutterBasePlayerMediaKitPlayer
      linux:
        dartPluginClass: FlutterBasePlayerMediaKitPlayer

dependencies:
  flutter:
    sdk: flutter
  flutter_base_player_platform_interface: ^0.1.6
  # flutter_base_player_platform_interface:
  #   path: ../flutter_base_player_platform_interface
  video_player: ^2.6.1
  media_kit: ^0.0.4+1
  media_kit_video: ^0.0.4
  media_kit_native_event_loop: ^1.0.2
  media_kit_libs_windows_video: ^1.0.1          # Windows package for video (& audio) native libraries.
  media_kit_libs_ios_video: ^1.0.3              # iOS package for video (& audio) native libraries.
  media_kit_libs_macos_video: ^1.0.3            # macOS package for video (& audio) native libraries.
  media_kit_libs_linux: ^1.0.1 
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=2.0.0"