name: flutter_base_player
description: Universal video player for flutter
repository: https://github.com/zhahouming/flutter_base_player/flutter_base_player
version: 0.1.0
homepage: https://github.com/zhahouming/flutter_base_player/flutter_base_player

flutter:
  plugin:
    platforms:
      android:
        dartPluginClass: FlutterBasePlayerVideoPlayer
      ios:
        dartPluginClass: FlutterBasePlayerVideoPlayer
      macos:
        dartPluginClass: FlutterBasePlayerVideoPlayer
      windows:
        dartPluginClass: FlutterBasePlayerDartVlcPlayer
      linux:
        dartPluginClass: FlutterBasePlayerDartVlcPlayer

dependencies:
  flutter:
    sdk: flutter
  flutter_base_player_platform_interface: ^0.1.0
  video_player: ^2.4.5
  video_player_macos: ^1.0.6
  dart_vlc: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=2.0.0"