name: flutter_base_player
description: A new Flutter package project.
version: 0.0.1
homepage:

flutter:
  plugin:
    platforms:
      android:
        dartPluginClass: FlutterBasePlayerVideoPlayer
      ios:
        dartPluginClass: FlutterBasePlayerVideoPlayer
      macos:
        dartPluginClass: FlutterBasePlayerVideoPlayer
      windows:
        dartPluginClass: FlutterBasePlayerDartVlcPlayer
      linux:
        dartPluginClass: FlutterBasePlayerDartVlcPlayer

dependencies:
  flutter:
    sdk: flutter
  flutter_base_player_platform_interface:
    path: ../flutter_base_player_platform_interface
  video_player: 2.4.5
  video_player_macos: 1.0.6
  dart_vlc: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"