name: ezplayer
description: easy video player for flutter
repository: https://github.com/zhahouming/flutter_base_player/ezplayer
version: 0.0.1
homepage: https://github.com/zhahouming/flutter_base_player/ezplayer

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_base_player: ^0.1.2
  volume_controller: ^2.0.3
  screen_brightness: ^0.2.1
  extension_widget: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
