name: ezplayer
description: easy video player for flutter
repository: https://github.com/zhahouming/flutter_base_player/ezplayer
version: 1.0.7
homepage: https://github.com/zhahouming/flutter_base_player/ezplayer

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_volume_controller: ^1.2.5
  screen_brightness: ^0.2.2
  extension_widget: ^0.0.1
  date_format: ^2.0.7
  wakelock_plus: ^1.1.1
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1
  http_parser: ^4.0.2
  http: ^0.13.5
  equatable: ^2.0.5
  flutter_colorpicker: ^1.0.3
  media_kit: ^1.1.7                              # Primary package.
  media_kit_video: ^1.1.8                        # For video rendering.
  media_kit_libs_video: ^1.0.1                   # Native video dependencies.

  # media_kit: ^0.0.11                             # Primary package.
  # media_kit_video: ^0.0.12                       # For video rendering.
  # media_kit_native_event_loop: ^1.0.4            # Support for higher number of concurrent instances & better performance.
  # media_kit_libs_android_video: ^1.0.6           # Android package for video native libraries.
  # media_kit_libs_ios_video: ^1.0.4               # iOS package for video native libraries.
  # media_kit_libs_macos_video: ^1.0.5             # macOS package for video native libraries.
  # media_kit_libs_windows_video: ^1.0.2           # Windows package for video native libraries.
  # media_kit_libs_linux: ^1.0.2                   # GNU/Linux dependency package.
  path: ^1.8.2

dependency_overrides:
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
